1. Refactored the function called "create_test_view_setup()" to loop over objects in a sequential fashion instead of nested. Gave it some kwargs like create_clients=True, create_following_lists=False.   2. Created another helper function called "get_potential_PetMatch_PetReport_pairs()" that will find PetMatch PetReport (lost,found) pairs that can be made (if any) and returns it as a list. This is used in the create_random_PetMatch() function for creating a potential PetMatch if one can be found with the test data generated.   3. Refactored ALL test cases to receive new return tuples when calling create_test_view_setup(). the "users" portion of the return tuple is now a tuple of its own (users, passwords) that can be unpacked in your test case. It is a beautiful refactor!   4. During refactor, I ran into a test error found in matching.VerificationTesting.test_post_verification_response. Amrutha, can you take a look at this?
===========================================
FAIL: test_post_verification_response (matching.tests.VerificationTesting)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/srv/epm/project/matching/tests.py", line 583, in test_post_verification_response

    self.assertEquals(sent_vote,new_lost_pet_vote)

AssertionError: '2' != u'1'

----------------------------------------------------------------------